version: "3"
services:
  app:
    container_name: react-admin_app
    build:
      context: ./docker/php
    volumes:
      - ${APP_PATH}:/app
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /app
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - TZ=${TZ}
  web:
    image: nginx:1.17-alpine
    container_name: react-admin_web
    depends_on:
      - app
    ports:
      - ${WEB_PORT}:80
    volumes:
      - ${APP_PATH}:/app
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - TZ=${TZ}
  db:
    image: mysql:8.0
    container_name: react-admin_db
    volumes:
      - db-store:/var/lib/mysql
      - ./docker/db/log:/var/log/mysql
      - ./docker/db/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - TZ=${TZ}
    ports:
      - ${DB_PORT}:3306
volumes:
  db-store: null
